# this configuration specifies endpoints for database , Redis , PostGreSql
#
spring :
  datasource:
    url : jdbc:postgresql://localhost:5432/bankdb
    username : superuser
    password : superpass
  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
    properties:
      hibernate:
        format_sql: true

  data :
    redis :
      host : localhost
      port : 6379

  server :
    port : 8080
